### ISSUE TITLE
Upsert flag on create_document causes TypeError

### ISSUE THREAD

**Issue by DanielArthurUK** [calmseas/aio-cosmos#1]
When using `upsert=True` on `CosmosClient.create_document`, a `TypeError` is thrown:

```python
>>> await client.create_document(database='my-db', container='my-container', partition_key='...', json={"id": "blah blah"}, upsert=True)
```

Throws:

```
Traceback (most recent call last):
  File "C:\python39\lib\concurrent\futures\_base.py", line 445, in result
    return self.__get_result()
  File "C:\python39\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "<console>", line 1, in <module>
  File "[REDACTED]\.venv\lib\site-packages\aio_cosmos\client.py", line 223, in create_document
    async with self.session.post(f'{self._get_writable()}/dbs/{database}/colls/{container}/docs',
  File "[REDACTED]\.venv\lib\site-packages\aiohttp\client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "[REDACTED]\.venv\lib\site-packages\aiohttp\client.py", line 557, in _request
    resp = await req.send(conn)
  File "[REDACTED]\.venv\lib\site-packages\aiohttp\client_reqrep.py", line 669, in send
    await writer.write_headers(status_line, self.headers)
  File "[REDACTED]\.venv\lib\site-packages\aiohttp\http_writer.py", line 130, in write_headers
    buf = _serialize_headers(status_line, headers)
  File "aiohttp\_http_writer.pyx", line 132, in aiohttp._http_writer._serialize_headers
  File "aiohttp\_http_writer.pyx", line 109, in aiohttp._http_writer.to_str
TypeError: Cannot serialize non-str key True
```

We can currently work around this issue by passing in the boolean as a string (i.e. `upsert='True'`) but the IDE raises warnings as the type hints expect a boolean.

I think we just need to cast the upsert flag to a string in `client.py`

**Comment by calmseas** [comment]
This is already fixed in 0.2.4, I just hadn't commit+tagged the release, will do now
